name: Pulls pre-compiled nuget and publishes them
on:
  push:
    branches:
      - main
  repository_dispatch:
    types: [TaleSpire-Modding-Pipelines/AutomationDlls]
    
jobs:
  build:
    runs-on: windows-latest
    steps:
      - name: Setup Nuget
        uses: nuget/setup-nuget@v1

      - name: Checkout
        uses: actions/checkout@v2
            
      - name: Download artifact
        uses: dawidd6/action-download-artifact@v2
        with:
          github_token: ${{ secrets.dll_pat }}
          workflow: build.yml
          branch: master
          path: .
          repo: TaleSpire-Modding-Pipelines/AutomationDlls
          
      - name: Publish
        run: |
          dotnet nuget push *.nupkg --api-key ${{ secrets.GITHUB_TOKEN }} --source https://nuget.pkg.github.com/${{ github.repository_owner }} --skip-duplicate
          dotnet nuget push *.nupkg --api-key ${{ secrets.NUGET_TOKEN }} --source https://api.nuget.org/v3/index.json --skip-duplicate
