name: Pulls pre-compiled nuget and publishes them
on:
  push:
    branches:
      - main
  repository_dispatch:
    types: [TaleSpire-Modding-Pipelines/AutomationDlls]
    
jobs:
  build:
    runs-on: windows-latest
    steps:
      - name: Setup Nuget
        uses: nuget/setup-nuget@v1

      - name: Checkout
        uses: actions/checkout@v2
            
      - name: Download artifact
        uses: dawidd6/action-download-artifact@v2
        with:
          github_token: ${{ secrets.dll_pat }}
          workflow: build.yml
          branch: master
          path: .
          repo: TaleSpire-Modding-Pipelines/AutomationDlls
          
          
      - name: Publish
        run: |
          cd dlls/BepinexDlls
          dotnet nuget push *.nupkg --api-key ${{ secrets.GITHUB_TOKEN }} --source https://nuget.pkg.github.com/${{ github.repository_owner }} --skip-duplicate
          cd ../TaleSpireDlls
          dotnet nuget push *.nupkg --api-key ${{ secrets.GITHUB_TOKEN }} --source https://nuget.pkg.github.com/${{ github.repository_owner }} --skip-duplicate

#       - name: Deploy Bepinex DLL Nuget
#         uses: tanaka-takayoshi/nuget-publish-to-github-packages-action@v2.1
#         with:
#           nupkg-path:  './dlls/BepinexDlls/TaleSpireBepInEx.5.4.10.nupkg'
#           repo-owner:  'TaleSpire-Modding-Pipelines'
#           gh-user:  'HolloFox'
#           token:  ${{ secrets.GITHUB_TOKEN }}
          
#       - name: Deploy TaleSpire DLL Nuget
#         uses: tanaka-takayoshi/nuget-publish-to-github-packages-action@v2.1
#         with:
#           nupkg-path:  './dlls/TaleSpireDlls/TaleSpire.0.0.1.nupkg'
#           repo-owner:  'TaleSpire-Modding-Pipelines'
#           gh-user:  'HolloFox'
#           token:  ${{ secrets.GITHUB_TOKEN }}
